language: node_js
node_js:
    - "node"
    - "lts/*"
addons:
    firefox: latest
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
before_deploy: yarn run build
deploy:
    - provider: pages
      skip_cleanup: true
      github-token: "$GH_TOKEN"
      target-branch: master
      repo: BuildrApp/BuildrApp.github.io
      local-dir: packages/Client/dist
      fqdn: buildr.zoweb.me
    - provider: heroku
      skip_cleanup: true
      api_key: "$HEROKU_TOKEN"
      app: buildr-backend